import type { DynamicOverride, DynamicOverrideMember } from './model'

export const MONKEYKING_API_BASELINE =
  '0588909e8603bb1e898c5cd592672aac26e4aaaa' as const

function members(
  kind: DynamicOverrideMember['kind'],
  names: readonly string[],
): DynamicOverrideMember[] {
  return names.map((name) => ({ name, kind }))
}

/**
 * Static extraction must never guess values that are computed by reflection,
 * generated sources, runtime delegates, or enum-backed keys. Each exception is
 * kept here with a source location and a reason so changes remain reviewable.
 */
export const dynamicOverrides: readonly DynamicOverride[] = [
  {
    id: 'dm-rhino-module',
    className: 'DmBindings',
    owner: 'dm',
    optional: true,
    module: {
      id: 'dm',
      name: 'dm',
      className: 'Dm',
      aliases: [],
      source: {
        path: 'app/src/main/java/com/monkeyking/runtime/api/augment/dm/DmBindings.kt',
        line: 42,
      },
    },
    reason:
      'DmBindings creates one script-local NativeObject named dm and reflects only the reviewed Dm facade plus the explicitly listed DmEngine extensions.',
    source: {
      path: 'app/src/main/java/com/monkeyking/runtime/api/augment/dm/DmBindings.kt',
      line: 42,
    },
    members: [{ name: 'setImage', kind: 'function' }],
  },
  {
    id: 'dm-java-facade-methods',
    className: 'Dm',
    owner: 'dm',
    sourceClassName: 'Dm',
    optional: true,
    includePublicMembers: true,
    excludeMembers: [
      'buffer',
      'cancel',
      'close',
      'getFrameInfo',
      'getLastFindTimings',
      'invoke',
      'keepScreen',
      'ocrAuto',
      'setImage',
      'setSimdEnabled',
      'useScreen',
    ],
    reason:
      'The Rhino binding reflects every public method declared by the generated Dm facade; inherited DmEngine methods are excluded here and added through a reviewed whitelist.',
    source: {
      path: 'libs/dm/src/main/java/com/monkeyking/dm/Dm.java',
      line: 7,
    },
  },
  {
    id: 'dm-engine-script-methods',
    className: 'DmEngine',
    owner: 'dm',
    sourceClassName: 'DmEngine',
    optional: true,
    includePublicMembers: true,
    excludeMembers: ['invoke', 'setImage'],
    reason:
      'DmBindings adds only these public DmEngine methods to the reflected script object; invoke and the overloaded Java setImage methods remain implementation details.',
    source: {
      path: 'app/src/main/java/com/monkeyking/runtime/api/augment/dm/DmBindings.kt',
      line: 42,
    },
  },
  {
    id: 'colors-reflected-tables',
    className: 'Colors',
    assignments: ['selfAssignmentProperties'],
    reason:
      'The public table properties are generated by mapping ColorTable singleton classes and lowercasing their reflected class names.',
    source: {
      path: 'app/src/main/java/com/monkeyking/runtime/api/augment/colors/Colors.kt',
      line: 149,
    },
    members: [
      { name: 'android', kind: 'property' },
      { name: 'css', kind: 'property' },
      { name: 'web', kind: 'property' },
      { name: 'material', kind: 'property' },
      {
        id: 'dynamic:colors.merged-table-entries',
        name: 'mergedTableEntries',
        kind: 'dynamic',
      },
    ],
  },
  {
    id: 'color-reflected-table-prototypes',
    className: 'ColorTable',
    owner: 'color',
    reason:
      'The Color function receives the reflected ColorTable singletons as its prototype chain, so the complete constant set is generated from those tables at runtime.',
    source: {
      path: 'app/src/main/java/com/monkeyking/core/image/ColorTable.kt',
      line: 9,
    },
    members: [
      {
        id: 'dynamic:color.table-entries',
        canonicalId: 'dynamic:colors.merged-table-entries',
        name: 'tableEntries',
        kind: 'dynamic',
      },
    ],
  },
  {
    id: 'global-reflected-classes',
    className: 'Classes',
    owner: 'global',
    idPrefix: 'global:',
    includeJvmFieldsAs: 'class',
    reason:
      'GlobalClasses resolves the public @JvmField declarations in Classes by name and exposes them as NativeJavaClass globals.',
    source: {
      path: 'app/src/main/java/com/monkeyking/runtime/api/augment/global/Classes.kt',
      line: 4,
    },
  },
  {
    id: 'selector-reflected-global-methods',
    className: 'UiSelector',
    owner: 'global',
    idPrefix: 'global:',
    includeAnnotatedMembers: true,
    reason:
      'Selector iterates UiSelector methods and installs the script-interface methods as global selector functions.',
    source: {
      path: 'app/src/main/java/com/monkeyking/runtime/api/augment/selector/Selector.kt',
      line: 44,
    },
  },
  {
    id: 'ui-proxy-properties',
    className: 'UIProxySurface',
    owner: 'ui',
    reason:
      'The UI augmentable proxies arbitrary script keys to the runtime UI object and view lookup, so the key set is script- and layout-dependent.',
    source: {
      path: 'app/src/main/java/com/monkeyking/runtime/api/augment/ui/UI.kt',
      line: 176,
    },
    members: [
      {
        id: 'dynamic:ui.proxy-properties',
        name: 'proxyProperties',
        kind: 'dynamic',
      },
    ],
  },
  {
    id: 'ui-widget-runtime-prototype',
    className: 'UIWidget',
    owner: 'ui.Widget',
    includeAnnotatedMembers: true,
    reason:
      'UI assigns the annotated UIWidget functions and the mutable __attrs__ registry to every ui.Widget prototype at runtime.',
    source: {
      path: 'app/src/main/java/com/monkeyking/runtime/api/augment/ui/UIWidget.kt',
      line: 28,
    },
    members: [{ name: '__attrs__', kind: 'property' }],
  },
  {
    id: 'websocket-reflected-fields',
    className: 'WebSocketFields',
    owner: 'webSocket',
    reason:
      'WebSocketFields reflects the CoreWebSocket companion properties by requested key.',
    source: {
      path: 'app/src/main/java/com/monkeyking/runtime/api/augment/web/WebSocketFields.kt',
      line: 13,
    },
    members: members('property', [
      'CODE_CLOSE_NORMAL',
      'CODE_CLOSE_GOING_AWAY',
      'CODE_CLOSE_PROTOCOL_ERROR',
      'CODE_CLOSE_UNSUPPORTED',
      'CODE_CLOSED_NO_STATUS',
      'CODE_CLOSE_ABNORMAL',
      'CODE_UNSUPPORTED_PAYLOAD',
      'CODE_POLICY_VIOLATION',
      'CODE_CLOSE_TOO_LARGE',
      'CODE_MANDATORY_EXTENSION',
      'CODE_SERVER_ERROR',
      'CODE_SERVICE_RESTART',
      'CODE_TRY_AGAIN_LATER',
      'CODE_BAD_GATEWAY',
      'CODE_TLS_HANDSHAKE_FAIL',
      'EVENT_CLOSED',
      'EVENT_CLOSING',
      'EVENT_FAILURE',
      'EVENT_TEXT',
      'EVENT_MESSAGE',
      'EVENT_BYTES',
      'EVENT_OPEN',
      'EVENT_MAX_REBUILDS',
    ]),
  },
  {
    id: 'websocket-java-instance',
    className: 'CoreWebSocket',
    sourceClassName: 'WebSocket',
    owner: 'webSocket.instance',
    includePublicMembers: true,
    reason:
      'The WebSocket constructor returns a Rhino-wrapped CoreWebSocket instance whose Java methods form the instance API.',
    source: {
      path: 'app/src/main/java/com/monkeyking/core/web/WebSocket.kt',
      line: 15,
    },
  },
  {
    id: 'mediainfo-runtime-result',
    className: 'MediainfoNativeObject',
    owner: 'mediainfo.result',
    includeAnnotatedMembers: true,
    reason:
      'MediainfoNativeObject installs stream-query functions from MediaInfo.StreamKind and metadata sections parsed from the inspected file.',
    source: {
      path: 'app/src/main/java/com/monkeyking/runtime/api/augment/mediainfo/MediainfoNativeObject.kt',
      line: 52,
    },
    members: [
      ...members('property', ['path', 'inform']),
      ...members('function', [
        'general',
        'video',
        'audio',
        'text',
        'other',
        'image',
        'menu',
        'max',
      ]),
      {
        id: 'dynamic:mediainfo.result.metadata',
        name: 'metadata',
        kind: 'dynamic',
      },
    ],
  },
  {
    id: 'zip-runtime-result',
    className: 'ZipNativeObject',
    owner: 'zip.result',
    includeAnnotatedMembers: true,
    reason:
      'Every zip operation returns ZipNativeObject, which installs its function and property lists at construction time.',
    source: {
      path: 'app/src/main/java/com/monkeyking/runtime/api/augment/zip/ZipNativeObject.kt',
      line: 94,
    },
    members: members('property', [
      'name',
      'path',
      'zipFile',
      'options',
      'zipParameters',
      'unzipParameters',
    ]),
  },
  {
    id: 'color-runtime-result',
    className: 'ColorNativeObject',
    owner: 'color.result',
    includeAnnotatedMembers: true,
    reason:
      'ColorNativeObject resolves mutators and forwarded Colors functions through its overridden has/get implementation.',
    source: {
      path: 'app/src/main/java/com/monkeyking/runtime/api/augment/colors/ColorNativeObject.kt',
      line: 30,
    },
    members: [
      { name: 'color', kind: 'property' },
      {
        id: 'dynamic:color.result.forwarded-functions',
        name: 'forwardedFunctions',
        kind: 'dynamic',
      },
    ],
  },
  {
    id: 'root-automator-runtime-result',
    className: 'RootAutomatorNativeObject',
    owner: 'rootAutomator.instance',
    reason:
      'RootAutomatorNativeObject forwards the public methods of its wrapped CoreRootAutomator object and binds returned functions.',
    source: {
      path: 'app/src/main/java/com/monkeyking/runtime/api/augment/automator/RootAutomatorNativeObject.kt',
      line: 31,
    },
    members: [
      {
        id: 'dynamic:rootAutomator.instance.forwarded-methods',
        name: 'forwardedMethods',
        kind: 'dynamic',
      },
    ],
  },
  {
    id: 'http-response-wrapper',
    className: 'ResponseWrapper',
    owner: 'http.response',
    reason:
      'ResponseWrapper builds the script-facing HTTP response object by inserting a fixed property set and dynamic lowercase header keys.',
    source: {
      path: 'app/src/main/java/com/monkeyking/runtime/api/augment/http/ResponseWrapper.kt',
      line: 24,
    },
    members: [
      ...members('property', [
        'request',
        'statusMessage',
        'statusCode',
        'body',
        'headers',
        'url',
        'method',
      ]),
      {
        id: 'dynamic:http.response.headers',
        name: 'headerFields',
        kind: 'dynamic',
      },
    ],
  },
  {
    id: 'http-response-body-runtime',
    className: 'ResponseBodyNativeObject',
    owner: 'http.response.body',
    includeAnnotatedMembers: true,
    reason:
      'ResponseBodyNativeObject adds annotated convenience functions while forwarding other keys to okhttp3.ResponseBody.',
    source: {
      path: 'app/src/main/java/com/monkeyking/runtime/api/augment/http/ResponseBodyNativeObject.kt',
      line: 49,
    },
    members: [
      { name: 'contentType', kind: 'property' },
      {
        id: 'dynamic:http.response.body.forwarded-members',
        name: 'forwardedMembers',
        kind: 'dynamic',
      },
    ],
  },
  {
    id: 'http-save-result-runtime',
    className: 'HttpSaveResult',
    owner: 'http.saveResult',
    includeAnnotatedMembers: true,
    reason:
      'HttpSaveResult installs fixed result getters and an annotated isSuccess function on the returned native object.',
    source: {
      path: 'app/src/main/java/com/monkeyking/runtime/api/augment/http/HttpSaveResult.kt',
      line: 21,
    },
    members: members('property', [
      'code',
      'path',
      'bytesCopied',
      'success',
      'error',
    ]),
  },
  {
    id: 'storage-runtime-result',
    className: 'StorageNativeObject',
    owner: 'storages.result',
    includeAnnotatedMembers: true,
    reason:
      'storages.create returns StorageNativeObject, which installs the annotated Getter methods plus name and size properties.',
    source: {
      path: 'app/src/main/java/com/monkeyking/runtime/api/augment/storages/StorageNativeObject.kt',
      line: 25,
    },
    members: members('property', ['name', 'size']),
  },
  {
    id: 'volatile-dispose-runtime-result',
    className: 'VolatileDisposeNativeObject',
    owner: 'threads.volatileResult',
    includeAnnotatedMembers: true,
    reason:
      'threads.volatile returns VolatileDisposeNativeObject and installs its annotated synchronization functions at construction time.',
    source: {
      path: 'app/src/main/java/com/monkeyking/runtime/api/augment/threads/VolatileDisposeNativeObject.kt',
      line: 29,
    },
  },
  {
    id: 'morse-code-runtime-result',
    className: 'MorseCodeNativeObject',
    owner: 'util.morseCode.result',
    includeAnnotatedMembers: true,
    reason:
      'util.morseCode returns MorseCodeNativeObject, which installs annotated functions and pattern/code accessors.',
    source: {
      path: 'app/src/main/java/com/monkeyking/runtime/api/augment/util/MorseCodeNativeObject.kt',
      line: 22,
    },
    members: members('property', ['pattern', 'code']),
  },
  {
    id: 'version-codes-search-result',
    className: 'VersionCodesInfo',
    owner: 'util.versionCodes.result',
    reason:
      'VersionCodes.Info.toNativeObject constructs the fixed search-result properties and valueOf function dynamically.',
    source: {
      path: 'app/src/main/java/com/monkeyking/runtime/api/augment/util/VersionCodes.kt',
      line: 88,
    },
    members: [
      ...members('property', [
        'versionCode',
        'apiLevel',
        'releaseName',
        'platformVersion',
        'internalCodename',
        'releaseDate',
        'releaseTimestamp',
      ]),
      { name: 'valueOf', kind: 'function' },
    ],
  },
  {
    id: 'pinyin-convert-result',
    className: 'PinyinResult',
    owner: 'pinyin.result',
    reason:
      'pinyin.convert attaches a bound compact function directly to each returned NativeArray.',
    source: {
      path: 'app/src/main/java/com/monkeyking/runtime/api/augment/pinyin/Pinyin.kt',
      line: 72,
    },
    members: [
      {
        name: 'compact',
        kind: 'function',
        canonicalId: 'pinyin.compact',
      },
    ],
  },
  {
    id: 'mime-legacy-prototype',
    className: 'MimeLegacyPrototype',
    owner: 'mime',
    reason:
      'runtime.api.Mime extends the pinned mime-util 2.1.3 MimeUtil2 class; these inherited public members come from that audited dependency while the Kotlin extractor reads every declared conversion helper and @JvmField MIME constant directly.',
    source: {
      path: 'app/src/main/java/com/monkeyking/runtime/api/Mime.kt',
      line: 11,
    },
    members: [
      ...members('property', ['DIRECTORY_MIME_TYPE', 'UNKNOWN_MIME_TYPE']),
      ...members('function', [
        'addKnownMimeType',
        'getKnownMimeTypes',
        'registerMimeDetector',
        'getExtension',
        'getFirstMimeType',
        'getType',
        'getMimeQuality',
        'getMimeDetector',
        'getMimeTypes',
        'getNativeOrder',
        'getPreferredMimeType',
        'getMostSpecificMimeType',
        'getSubtype',
        'isMimeTypeKnown',
        'isTextMimeType',
        'unregisterMimeDetector',
        'getQuality',
        'getInputStreamForURL',
      ]),
    ],
  },
  {
    id: 'mime-runtime-result',
    className: 'JsMime',
    owner: 'mime.result',
    includeJvmFieldsAs: 'property',
    reason:
      'Calling mime returns JsMime, whose @JvmField values are exposed by Rhino as the parsed result object.',
    source: {
      path: 'app/src/main/java/com/monkeyking/runtime/api/augment/mime/JsMime.kt',
      line: 9,
    },
    members: members('function', ['toString', 'toStringReadable']),
  },
  {
    id: 'sqlite-database-runtime-result',
    className: 'Database',
    owner: 'sqlite.database',
    includePublicMembers: true,
    reason:
      'sqlite returns a Rhino-wrapped Database; all public members declared by the pinned Java wrapper are extracted individually from source, and the remaining SQLiteOpenHelper members come from compileSdk 36 declared by version.properties.',
    source: {
      path: 'app/src/main/java/com/monkeyking/core/database/Database.java',
      line: 21,
    },
    members: members('function', [
      'getDatabaseName',
      'getReadableDatabase',
      'getWritableDatabase',
      'onConfigure',
      'onDowngrade',
      'setIdleConnectionTimeout',
      'setLookasideConfig',
      'setOpenParams',
      'setWriteAheadLoggingEnabled',
    ]),
  },
  {
    id: 'sqlite-cursor-wrapper',
    className: 'CursorWrapper',
    owner: 'sqlite.cursor',
    includeAnnotatedMembers: true,
    reason:
      'SQLite.CursorWrapper delegates the Android Cursor interface from the pinned compileSdk 36 API and adds the annotated script convenience methods.',
    source: {
      path: 'app/src/main/java/com/monkeyking/runtime/api/SQLite.kt',
      line: 53,
    },
    members: members('function', [
      'close',
      'copyStringToBuffer',
      'deactivate',
      'getBlob',
      'getColumnCount',
      'getColumnIndex',
      'getColumnIndexOrThrow',
      'getColumnName',
      'getColumnNames',
      'getCount',
      'getDouble',
      'getExtras',
      'getFloat',
      'getInt',
      'getLong',
      'getNotificationUri',
      'getNotificationUris',
      'getPosition',
      'getShort',
      'getString',
      'getType',
      'getWantsAllOnMoveCalls',
      'isAfterLast',
      'isBeforeFirst',
      'isClosed',
      'isFirst',
      'isLast',
      'isNull',
      'move',
      'moveToFirst',
      'moveToLast',
      'moveToNext',
      'moveToPosition',
      'moveToPrevious',
      'registerContentObserver',
      'registerDataSetObserver',
      'requery',
      'respond',
      'setExtras',
      'setNotificationUri',
      'setNotificationUris',
      'unregisterContentObserver',
      'unregisterDataSetObserver',
    ]),
  },
  {
    id: 'ocr-mlkit-enum-key',
    className: 'OcrMLKit',
    key: 'mlkit',
    reason:
      'The nested module key is computed from OcrMode.MLKIT.value; the enum value is the stable public name mlkit.',
    source: {
      path: 'app/src/main/java/com/monkeyking/runtime/api/augment/ocr/OcrMLKit.kt',
      line: 17,
    },
  },
  {
    id: 'ocr-paddle-enum-key',
    className: 'OcrPaddle',
    key: 'paddle',
    reason:
      'The nested module key is computed from OcrMode.PADDLE.value; the enum value is the stable public name paddle.',
    source: {
      path: 'app/src/main/java/com/monkeyking/runtime/api/augment/ocr/OcrPaddle.kt',
      line: 36,
    },
  },
  {
    id: 'ocr-rapid-enum-key',
    className: 'OcrRapid',
    key: 'rapid',
    reason:
      'The nested module key is computed from OcrMode.RAPID.value; the enum value is the stable public name rapid.',
    source: {
      path: 'app/src/main/java/com/monkeyking/runtime/api/augment/ocr/OcrRapid.kt',
      line: 17,
    },
  },
]
